'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pages={home:'Главная',servers:'Серверы',telegram:'Telegram MTProxy',proxy:'Настройка прокси',history:'Клиенты и история',diagnostics:'Диагностика',settings:'Настройки'};
const modes={default:'Как в общих настройках',all_vpn:'Всё через VPN',selected:'Только сайты из списков через VPN',except:'Всё через VPN, кроме исключений',direct:'Напрямую, без VPN'};
let state=null,page=location.hash.slice(1)||'home',sourceTab='all',search='',sort='quality',historyData=null,dialogSubmit=null,noticeTimer;
const date=t=>t?new Date(t*1000).toLocaleString('ru-RU'):'Ещё не проверено';
const bytes=n=>{n=Number(n)||0;let u=0;while(n>=1024&&u<4){n/=1024;u++}return n.toFixed(u?1:0)+' '+['Б','КБ','МБ','ГБ','ТБ'][u]};
const badge=(text,cls='')=>`<span class="badge ${cls}">${esc(text)}</span>`;
const button=(text,action,id='',cls='quiet small')=>`<button class="${cls}" data-action="${action}" data-id="${esc(id)}">${esc(text)}</button>`;
function notice(text,error=false){clearTimeout(noticeTimer);$('#notice').innerHTML=`<div class="notice ${error?'error':'success'}">${esc(text)}</div>`;noticeTimer=setTimeout(()=>$('#notice').innerHTML='',12000)}
async function api(path,body){const r=await fetch('api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-Boris-Request':'1'},body:body===undefined?undefined:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error||'Ошибка запроса');return j}
async function mutate(path,body){try{const r=await api(path,body);notice(r.note|| (r.job_id?'Задача запущена. Результат появится ниже.':r.errors?.length?`Добавлено ${r.imported}. Есть ошибки импорта — смотрите результат.`:'Готово'));if(r.errors?.length)showDetails('Результат импорта',r);await refresh();return r}catch(e){notice(e.message,true);throw e}}
function field(name,title,value='',type='text'){return `<label for="f-${name}">${esc(title)}</label><input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}">`}
function check(name,title,value){return `<label class="check"><input type="checkbox" name="${name}" ${value?'checked':''}>${esc(title)}</label>`}
function select(name,title,value,options){return `<label>${esc(title)}</label><select name="${name}">${Object.entries(options).map(([k,v])=>`<option value="${esc(k)}" ${k===value?'selected':''}>${esc(v)}</option>`).join('')}</select>`}
function area(name,title,value){return `<label>${esc(title)}</label><textarea name="${name}">${esc(value)}</textarea>`}
function modal(title,html,submit){$('#dialog-body').innerHTML=`<h2>${esc(title)}</h2>${html}`;dialogSubmit=submit;$('#dialog-form button[type=submit]').hidden=!submit;$('#dialog').showModal()}
function showDetails(title,data){modal(title,`<pre>${esc(JSON.stringify(data,null,2))}</pre>`,null)}
function serverName(id){return state.config.servers.find(s=>s.id===id)?.name||'Не выбран'}
function availability(result,key){if(!result)return badge('Не проверено');if(key==='telegram')return badge(result.telegram?.status==='tcp_ok'?'TCP доступен':result.telegram?'Недоступен':'Не проверено',result.telegram?.status==='tcp_ok'?'ok':'');return badge(result[key+'_ok']?'Доступны':'Ограничены',result[key+'_ok']?'ok':'warn')}
function topJobs(){const jobs=state.jobs.slice(-3);$('#jobs').innerHTML=jobs.map(j=>`<div class="job">${j.state==='running'?'◌':j.state==='done'?'✓':'!'} ${esc(j.title)} · ${j.state==='running'?'Выполняется':j.state==='done'?'Завершено':esc(j.error||'Остановлено')} ${j.result?button('Результат','job-result',j.id):''}</div>`).join('');if(state.checks.running)$('#jobs').innerHTML+=`<progress max="${state.checks.total||1}" value="${state.checks.done}"></progress>`}
function home(){const c=state.config,s=c.settings,r=state.runtime,selected=c.servers.find(x=>x.id===r.selected),health=state.results[r.selected];return `<section class="panel hero"><div class="row between"><div>${badge(r.core&&selected?'Подключение выбрано':r.core?'Ожидание рабочего сервера':'Нужно внимание',r.core&&selected?'ok':'warn')}<h2>${esc(selected?.name||'Добавьте подписку или выберите сервер')}</h2><p class="lead">${esc(state.selection_reason)}</p></div>${button('Проверить сейчас','check','','')}</div><div class="row">${availability(health,'foreign')} ${availability(health,'russian')} ${badge(health?.latency_ms?health.latency_ms+' мс':'Задержка неизвестна')}</div></section><section class="panel"><h2>Выбор сервера</h2><div class="row"><button data-action="select-auto" class="${s.selection==='auto'?'':'quiet'}">Автоматически</button><select id="manual-choice" aria-label="Ручной выбор сервера"><option value="">Выберите сервер вручную</option>${c.servers.filter(x=>x.enabled&&!x.error).map(x=>`<option value="${x.id}" ${r.selected===x.id?'selected':''}>${esc(x.name)} · ${esc(x.outbound.type)}</option>`).join('')}</select>${button('Выбрать','select-home','','quiet')}</div><p class="muted">Текущий режим: <b>${s.selection==='auto'?'Автоматический':'Ручной'}</b>. ${s.manual_failover?'При отказе разрешена автоматическая замена.':'Автоматическая замена ручного выбора отключена.'}</p></section><div class="grid">${[['HTTP',s.http_enabled,s.http_port],['SOCKS5',s.socks_enabled,s.socks_port],['Telegram MTProxy',r.telegram,s.telegram_port]].map(([name,on,port])=>`<section class="panel"><h3>${name}</h3>${badge(on?'Включён':'Выключен',on?'ok':'')}<div class="stat">${port}</div><small>Порт подключения</small></section>`).join('')}</div><div class="grid two"><section class="panel"><h2>Сейчас подключены</h2><div class="stat">${state.active.length+Object.values(state.telegram_stats).reduce((n,x)=>n+(x.connections||0),0)}</div><p class="muted">Соединений через ваши прокси</p><a href="#history">Открыть клиентов и историю →</a></section><section class="panel"><h2>Последние события</h2>${state.events.slice(0,4).map(e=>`<div class="connection">${esc(e.message)} ${e.count>1?badge('×'+e.count):''}<small><br>${date(e.ts)}</small></div>`).join('')||'<p class="muted">Пока нет событий</p>'}</section></div>`}
function servers(){const c=state.config;let rows=c.servers.filter(s=>(sourceTab==='all'||s.source_id===sourceTab)&&s.name.toLowerCase().includes(search.toLowerCase()));rows.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'ru'):sort==='latency'?(state.results[a.id]?.latency_ms??99999)-(state.results[b.id]?.latency_ms??99999):quality(a)-quality(b));const src=c.sources.find(x=>x.id===sourceTab);return `<div class="row between toolbar"><div class="row">${button('Добавить подписку','source-new','','')}${button('Добавить серверы','import','','quiet')}</div>${button('Проверить все','check','','quiet')}</div><div class="tabs">${[['all','Все серверы'],...c.sources.map(s=>[s.id,s.name]),['manual','Вручную']].map(([id,n])=>`<button class="${sourceTab===id?'selected':''}" data-action="source-tab" data-id="${id}">${esc(n)}</button>`).join('')}</div>${src?`<section class="panel"><div class="row between"><div><h2>${esc(src.name)}</h2><small>Обновлено: ${date(src.updated_at)} · Получено: ${src.received??'—'} · Импортировано: ${src.imported??'—'}</small></div><div class="row">${button('Обновить подписку','refresh-source',src.id)}${button('Настроить','source-edit',src.id)}${button('Результат импорта','source-result',src.id)}</div></div>${src.partial?'<p class="bad-text">Частичное обновление: прежние подключения сохранены.</p>':''}${src.traffic?.total?`<p>Трафик: ${bytes((src.traffic.upload||0)+(src.traffic.download||0))} / ${bytes(src.traffic.total)}</p>`:''}</section>`:''}<section class="panel"><div class="toolbar"><input id="server-search" placeholder="Поиск по названию" value="${esc(search)}"><select id="server-sort"><option value="quality" ${sort==='quality'?'selected':''}>По доступности</option><option value="latency" ${sort==='latency'?'selected':''}>По задержке</option><option value="name" ${sort==='name'?'selected':''}>По названию</option></select></div><div class="table-wrap"><table><thead><tr><th>Сервер / источник</th><th>Задержка</th><th>Зарубежные</th><th>Российские</th><th>Telegram</th><th>Управление</th></tr></thead><tbody>${rows.map(s=>{const h=state.results[s.id],src=c.sources.find(x=>x.id===s.source_id);return `<tr><td><b>${esc(s.name)}</b> ${state.runtime.selected===s.id?badge('Выбран','ok'):''}<small>${esc(s.outbound.type)} · ${esc(src?.name||'Вручную')}</small>${s.error?`<small class="bad-text">${esc(s.error)}</small>`:''}</td><td>${h?.latency_ms?`${h.latency_ms} мс`:'—'}<small>${h?date(h.checked_at):'Не проверено'}</small></td><td>${availability(h,'foreign')}</td><td>${availability(h,'russian')}</td><td>${availability(h,'telegram')}</td><td><div class="row">${button('Выбрать','select',s.id)}${button('Подробнее','server-detail',s.id)}${button(s.enabled?'Выключить':'Включить','server-toggle',s.id)}${button(s.auto?'Авто: да':'Авто: нет','server-auto',s.id)}</div></td></tr>`}).join('')}</tbody></table>${rows.length?'':'<div class="empty">Серверов пока нет. Добавьте подписку или вставьте ссылки подключений.</div>'}</div></section>`}
function quality(s){const h=state.results[s.id];return !s.enabled||s.error?1e9:!h?.foreign_ok?1e8:(!h.russian_ok?1e6:0)+(h.latency_ms||99999)}
function secretField(value,id){return `<div class="field-row"><input type="password" readonly value="${esc(value)}" id="${id}" aria-label="Секрет подключения">${button('Показать','reveal',id)}${button('Копировать','copy-field',id)}</div>`}
function clients(telegram=false){const c=state.config;return `<div class="toolbar">${button('Добавить клиента','client-new','','')}${telegram?button(c.settings.telegram_enabled?'Выключить MTProxy':'Включить MTProxy','tg-toggle','','quiet'):''}</div>${telegram?`<section class="panel"><div class="row between"><div><h2>Telegram MTProxy</h2>${badge(state.runtime.telegram?'Процесс работает':'Процесс остановлен',state.runtime.telegram?'ok':'warn')}<p class="muted">Порт ${c.settings.telegram_port} · ${esc(c.settings.public_host||'Адрес подключения ещё не указан')}</p></div>${button('Адрес и порты','proxy-settings','','quiet')}</div>${state.runtime.telegram_error?`<p class="bad-text">${esc(state.runtime.telegram_error)}</p>`:''}<small>Процесс и TCP-доступность проверяются автоматически. Отправку сообщений подтверждает проверка в Telegram на устройстве.</small></section>`:''}<div class="grid two">${c.clients.map(u=>{const t=state.telegram_stats[u.username];return `<section class="panel"><div class="row between"><h2>${esc(u.name)}</h2>${badge(u.enabled?'Доступ включён':'Отключён',u.enabled?'ok':'')}</div><div class="row">${['http','socks','telegram'].filter(k=>u[k]).map(k=>badge(k.toUpperCase())).join('')}${t?.connections?badge(t.connections+' соединений Telegram','ok'):''}</div><label>Логин HTTP / SOCKS5</label><div class="mono">${esc(u.username)}</div><label>Пароль HTTP / SOCKS5</label>${secretField(u.password,'pass-'+u.id)}<label>Полный секрет MTProxy</label>${secretField(u.telegram_secret,'secret-'+u.id)}<div class="actions">${button('Ссылка и QR','client-link',u.id)}${button('Настроить','client-edit',u.id)}${button('Отключить соединения','disconnect',u.id)}</div><small>Маршрутизация: ${esc(modes[u.route_mode])} · Учтено за месяц: ${bytes((state.usage[u.id]?.upload||0)+(state.usage[u.id]?.download||0))}</small></section>`}).join('')}</div>`}
function proxy(){return `<section class="panel"><div class="row between"><div><h2>HTTP и SOCKS5</h2><p class="muted">Общие адрес, порты и переключатели. Доступы и режим маршрутизации задаются в карточке клиента.</p></div>${button('Настроить адрес и порты','proxy-settings','','')}</div></section>${clients(false)}`}
function history(){const active=[...state.active,...state.telegram_active];return `<section class="panel"><div class="row between"><h2>Активные подключения · ${active.length}</h2>${button('Обновить историю','load-history')}</div><div class="table-wrap">${sessionTable(active)}</div><small>HTTP/SOCKS5: отдельные соединения. Telegram: наблюдаемый период активности клиента; IP ядро MTProxy не предоставляет.</small></section><section class="panel"><h2>История подключений</h2><div class="table-wrap">${sessionTable(historyData?.sessions||[])}</div></section>`}
function sessionTable(rows){return rows.length?`<table><thead><tr><th>Клиент</th><th>Протокол</th><th>IP / назначение</th><th>Начало / окончание</th><th>Передано / получено</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.protocol)}</td><td>${esc(x.ip)}<small>${esc(x.destination)}</small></td><td>${date(x.started)}<small>${x.ended?date(x.ended):'Подключён сейчас'}</small></td><td>${bytes(x.upload)} / ${bytes(x.download)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Подключений нет</div>'}
function diagnostics(){return `<section class="panel"><h2>Проверить приложение</h2><p class="muted">Проверка ядра, серверов, доступности сайтов и входных портов. Результат доступен в карточке завершённой задачи.</p><div class="actions">${button('Проверить всё','diagnostics','','')}${button('Восстановить сервисы','restart','','quiet')}${button('Отчёт без секретов','report','','quiet')}</div></section><section class="panel"><h2>События</h2>${(historyData?.events||state.events).map(e=>`<div class="connection">${badge(e.kind)} ${esc(e.message)} ${e.count>1?badge('×'+e.count):''}<small><br>${date(e.ts)}</small></div>`).join('')}</section>`}
function settings(){const c=state.config;return `<section class="panel"><h2>Маршрутизация</h2><p>${esc(modes[c.routing.mode])}</p><p class="muted">Списки сайтов, прямые исключения и правила для отдельных клиентов. Прямое соединение выполняется с Home Assistant без VPN.</p><div class="actions">${button('Настроить правила','routing','','')}${button('Обновить списки','rules','','quiet')}${button('Проверить адрес','route-test','','quiet')}</div></section><div class="grid two"><section class="panel"><h2>Автоматическая работа</h2><p class="muted">Периодичность проверок, контрольные сайты и автоматическая замена сервера.</p>${button('Настроить','automation','','quiet')}</section><section class="panel"><h2>Хранение и очистка</h2><p>История: ${c.settings.history_days} дней · ${bytes(state.storage_bytes)} / ${c.settings.history_mb} МБ</p><div class="actions">${button('Настроить','retention')}${button('Подчистить сейчас','cleanup')}${button('Очистить историю','clear-history','','danger small')}</div></section></div><section class="panel"><h2>Доступ и безопасность</h2><p class="muted">Доверенные адреса без пароля, блокировки, разрешённые сети, фильтр страны и ограничения подключений.</p>${button('Настроить','security','','quiet')}</section><section class="panel"><h2>Резервная копия и откат</h2><p class="muted">Копия содержит пароли, секреты и ссылки подписок. Для отката приложения используйте также резервную копию дополнения Home Assistant.</p><div class="actions"><a class="button quiet" href="api/backup" download>Скачать настройки</a>${button('Восстановить настройки','restore','','quiet')}<a class="button quiet" href="https://github.com/barawkaa/proxy-ot-borisa/tree/archive/v4.0.2" target="_blank" rel="noreferrer">Исходная версия 4.0.2</a></div></section><details class="panel"><summary>Дополнительные данные и перенос из 4.x</summary><p class="muted">Исходные данные сохраняются для проверки переноса и отката. Неизвестные старые поля не применяются молча.</p>${button('Отчёт переноса','migration')}${button('Старые дополнительные настройки','legacy')}</details>`}
function render(){if(!state)return;page=pages[page]?page:'home';$('#page-title').textContent=pages[page];$('#nav').innerHTML=Object.entries(pages).map(([k,v])=>`<a class="${page===k?'active':''}" href="#${k}">${v}</a>`).join('');$('#connection-text').textContent=state.runtime.core?'Приложение запущено':'Требуется внимание';$('#connection-dot').className=state.runtime.core?'good':'bad-text';topJobs();$('#content').innerHTML=({home,servers,telegram:()=>clients(true),proxy,history,diagnostics,settings}[page])();if(state.boot_error)$('#notice').innerHTML=`<div class="notice error">${esc(state.boot_error)}</div>`}
async function refresh(){try{state=await api('state');if(!$('#dialog').open&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))render();else topJobs()}catch(e){$('#connection-text').textContent='Нет связи с интерфейсом';notice(e.message,true)}}
function editClient(id){const u=state.config.clients.find(x=>x.id===id)||{name:'',http:true,socks:true,telegram:true,enabled:true,route_mode:'default',monthly_limit_gb:0};modal(id?'Настройка клиента':'Новый клиент',field('name','Имя клиента',u.name)+check('enabled','Доступ включён',u.enabled)+check('http','HTTP',u.http)+check('socks','SOCKS5',u.socks)+check('telegram','Telegram MTProxy',u.telegram)+select('route_mode','Маршрутизация',u.route_mode,modes)+(id?field('username','Логин',u.username)+field('password','Пароль',u.password)+field('telegram_secret','Полный секрет MTProxy',u.telegram_secret):'')+field('monthly_limit_gb','Лимит трафика, ГБ в месяц (0 — без лимита)',u.monthly_limit_gb,'number')+field('expires_at','Окончание доступа (необязательно)',u.expires_at?new Date(u.expires_at*1000).toISOString().slice(0,16):'','datetime-local')+area('notes','Примечание',u.notes||'')+(id?`<div class="actions">${button('Перевыпустить доступы','rotate',id,'danger small')}${button('Удалить клиента','delete-client',id,'danger small')}</div>`:''),async f=>{const b={id,name:f.get('name'),route_mode:f.get('route_mode'),monthly_limit_gb:Number(f.get('monthly_limit_gb')),notes:f.get('notes'),expires_at:f.get('expires_at')?new Date(f.get('expires_at')).getTime()/1000:0};for(const k of ['enabled','http','socks','telegram'])b[k]=f.has(k);if(id)for(const k of ['username','password','telegram_secret'])b[k]=f.get(k);await mutate('client',b)})}
function editSource(id){const s=state.config.sources.find(x=>x.id===id)||{enabled:true,auto:true,interval:3600};modal('Подписка',field('name','Название',s.name)+field('url','Ссылка подписки',s.url,'url')+field('interval','Обновлять каждые, минут',s.interval/60,'number')+check('enabled','Подписка включена',s.enabled)+check('auto','Использовать в автоматическом выборе',s.auto)+(id?button('Удалить подписку и её серверы','delete-source',id,'danger small'):''),async f=>mutate('source',{id,name:f.get('name'),url:f.get('url'),interval:Number(f.get('interval'))*60,enabled:f.has('enabled'),auto:f.has('auto')}))}
function jsonEditor(title,section,value){modal(title,area('json','Дополнительные настройки (JSON)',JSON.stringify(value,null,2)),async f=>mutate('settings',{[section]:JSON.parse(f.get('json'))}))}
function download(name,obj){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
const handlers={
'check':()=>mutate('check',{}),'diagnostics':()=>mutate('diagnostics',{}),'restart':()=>mutate('restart',{}),'rules':()=>mutate('rules',{}),
'select-auto':()=>mutate('select',{id:''}),'select-home':()=>{const id=$('#manual-choice').value;if(id)return mutate('select',{id})},'select':id=>mutate('select',{id}),
'source-tab':id=>{sourceTab=id;render()},'source-new':()=>editSource(),'source-edit':editSource,'refresh-source':id=>mutate('refresh',{id}),
'source-result':id=>showDetails('Результат импорта',state.config.sources.find(x=>x.id===id)),
'delete-source':async id=>{if(confirm('Удалить подписку и её серверы?')){await mutate('source',{id,delete:true});$('#dialog').close();sourceTab='all';render()}},
'import':()=>modal('Добавить отдельные серверы',area('text','Вставьте ссылки, JSON или Clash YAML',''),async f=>mutate('import',{text:f.get('text')})),
'server-toggle':id=>mutate('server',{id,enabled:!state.config.servers.find(x=>x.id===id).enabled}),
'server-auto':id=>mutate('server',{id,auto:!state.config.servers.find(x=>x.id===id).auto}),
'server-detail':id=>{const s=state.config.servers.find(x=>x.id===id);modal(s.name,`<p>${esc(s.outbound.type)} · ${esc(s.outbound.server)}:${s.outbound.server_port}</p><pre>${esc(JSON.stringify(state.results[id]||{status:'Не проверено'},null,2))}</pre>${field('name','Название',s.name)}${field('priority','Приоритет при равном качестве',s.priority,'number')}<div class="actions">${button('Удалить','delete-server',id,'danger small')}</div>`,async f=>mutate('server',{id,name:f.get('name'),priority:Number(f.get('priority'))}))},
'delete-server':async id=>{if(confirm('Удалить сервер? При обновлении подписки он может появиться снова.')){await mutate('server',{id,delete:true});$('#dialog').close();render()}},
'client-new':()=>editClient(),'client-edit':editClient,'disconnect':id=>mutate('disconnect',{id}),
'delete-client':async id=>{if(confirm('Удалить клиента и отозвать доступ?')){await mutate('client',{id,delete:true});$('#dialog').close();render()}},
'rotate':async id=>{if(confirm('Старые пароль и ссылка перестанут работать. Продолжить?')){await mutate('client',{id,rotate:true});$('#dialog').close();render()}},
'reveal':id=>{const input=document.getElementById(id);input.type=input.type==='password'?'text':'password'},
'copy-field':async id=>{const input=document.getElementById(id);try{await navigator.clipboard.writeText(input.value);notice('Скопировано')}catch{input.type='text';input.select();notice('Выделено. Нажмите Ctrl+C.')}},
'client-link':id=>{const u=state.config.clients.find(x=>x.id===id);modal('Подключение: '+u.name,u.tg_url?`<img class="qr" src="api/qr/${id}" alt="QR подключения"><label>Ссылка Telegram</label>${secretField(u.tg_url,'tg-link')}<div class="actions"><a class="button" href="${esc(u.tg_url)}">Открыть Telegram</a></div>`:'<p>Сначала укажите адрес подключения в разделе «Настройка прокси».</p>',null)},
'load-history':async()=>{historyData=await api('history');render()},
'job-result':id=>showDetails('Результат',state.jobs.find(x=>x.id===id)?.result),
'cleanup':()=>mutate('cleanup',{}),'clear-history':()=>{if(confirm('Удалить историю соединений и событий? Доступы сохранятся.'))return mutate('cleanup',{clear:true})},
'tg-toggle':()=>mutate('settings',{settings:{telegram_enabled:!state.config.settings.telegram_enabled}}),
'proxy-settings':()=>{const s=state.config.settings;modal('Адрес и порты',field('public_host','Адрес подключения (домен или IP, без протокола)',s.public_host)+field('http_port','Порт HTTP',s.http_port,'number')+field('socks_port','Порт SOCKS5',s.socks_port,'number')+field('telegram_port','Порт MTProxy',s.telegram_port,'number')+check('http_enabled','HTTP включён',s.http_enabled)+check('socks_enabled','SOCKS5 включён',s.socks_enabled)+check('telegram_enabled','MTProxy включён',s.telegram_enabled)+field('front_domain','Домен Fake TLS для новых клиентов',s.front_domain),async f=>{const b={};for(const k of ['public_host','front_domain'])b[k]=f.get(k);for(const k of ['http_port','socks_port','telegram_port'])b[k]=Number(f.get(k));for(const k of ['http_enabled','socks_enabled','telegram_enabled'])b[k]=f.has(k);await mutate('settings',{settings:b})})},
'routing':()=>{const r=state.config.routing;modal('Маршрутизация',select('mode','Общий режим',r.mode,Object.fromEntries(Object.entries(modes).filter(([k])=>k!=='default')))+area('vpn_domains','Домены через VPN — по одному в строке',r.vpn_domains.join('\n'))+area('direct_domains','Домены напрямую — по одному в строке',r.direct_domains.join('\n'))+area('vpn_ips','IP/CIDR через VPN',r.vpn_ips.join('\n'))+area('direct_ips','IP/CIDR напрямую',r.direct_ips.join('\n'))+area('sources','Обновляемые списки (JSON)',JSON.stringify(r.sources,null,2))+area('presets','Наборы доменов: openai, youtube, discord, telegram, spotify…',r.presets.join('\n')),async f=>{const b={mode:f.get('mode'),sources:JSON.parse(f.get('sources'))};for(const k of ['vpn_domains','direct_domains','vpn_ips','direct_ips','presets'])b[k]=f.get(k).split('\n').map(x=>x.trim()).filter(Boolean);await mutate('settings',{routing:b})})},
'automation':()=>{const s=state.config.settings;const titles={check_interval:'Текущий сервер, секунд',scan_interval:'Задержка всех серверов, секунд',availability_interval:'Доступность сайтов, секунд',subscription_interval:'Подписки по умолчанию, секунд',parallel_checks:'Одновременных проверок',switch_margin_ms:'Улучшение задержки для переключения, мс',switch_hold_seconds:'Минимальная пауза между улучшениями, секунд'};modal('Автоматическая работа',Object.entries(titles).map(([k,t])=>field(k,t,s[k],'number')).join('')+check('manual_failover','Заменять ручной выбор при отказе',s.manual_failover)+area('foreign_urls','Зарубежные контрольные HTTPS-адреса',s.foreign_urls.join('\n'))+area('russian_urls','Российские контрольные HTTPS-адреса',s.russian_urls.join('\n'))+area('service_urls','Отдельно проверяемые сервисы',s.service_urls.join('\n')),async f=>{const b={manual_failover:f.has('manual_failover')};for(const k of Object.keys(titles))b[k]=Number(f.get(k));for(const k of ['foreign_urls','russian_urls','service_urls'])b[k]=f.get(k).split('\n').map(x=>x.trim()).filter(Boolean);await mutate('settings',{settings:b})})},
'retention':()=>{const s=state.config.settings;const titles={history_days:'Хранить дней',history_records:'Максимум соединений в истории',event_records:'Максимум событий',history_mb:'Предел хранилища, МБ'};modal('Хранение данных',Object.entries(titles).map(([k,t])=>field(k,t,s[k],'number')).join(''),async f=>mutate('settings',{settings:Object.fromEntries(Object.keys(titles).map(k=>[k,Number(f.get(k))]))}))},
'security':()=>jsonEditor('Дополнительные параметры доступа','security',state.config.security),
'route-test':()=>modal('Проверить маршрут',field('host','Домен или IP')+select('client_id','Клиент','',{'':'Общие настройки',...Object.fromEntries(state.config.clients.map(x=>[x.id,x.name]))}),async f=>{const r=await api('route-test',Object.fromEntries(f));notice(`${r.route}: ${r.reason}`)}),
'restore':()=>modal('Восстановить настройки',area('backup','Вставьте содержимое резервной копии JSON',''),async f=>{if(!confirm('Заменить текущие настройки данными из копии?'))throw Error('Отменено');await mutate('restore',{config:JSON.parse(f.get('backup')).config})}),
'migration':()=>showDetails('Перенос из 4.x',state.config.migration), 'legacy':()=>showDetails('Исходные дополнительные данные',state.config.legacy),
'report':()=>download('proxy-boris-diagnostics.json',{version:state.version,runtime:state.runtime,checks:state.checks,servers:state.config.servers.map(x=>({id:x.id,protocol:x.outbound.type,error:x.error})),events:state.events})
};
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;e.preventDefault();b.disabled=true;try{await handlers[b.dataset.action]?.(b.dataset.id)}catch(e){notice(e.message,true)}finally{b.disabled=false}});
document.addEventListener('change',e=>{if(e.target.id==='server-search'){search=e.target.value;render()}if(e.target.id==='server-sort'){sort=e.target.value;render()}});
$('#dialog-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{if(dialogSubmit)await dialogSubmit(new FormData(e.target));$('#dialog').close();render()}catch(e){notice(e.message,true)}finally{b.disabled=false}});
$('#cancel-dialog').onclick=()=>$('#dialog').close();$('#refresh-view').onclick=refresh;
window.addEventListener('hashchange',async()=>{page=location.hash.slice(1);if(['history','diagnostics'].includes(page))historyData=await api('history');render()});
refresh();setInterval(refresh,10000);
